# Generated by Django 3.1.4 on 2021-01-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositionTitle', models.CharField(max_length=155)),
                ('date', models.CharField(max_length=155)),
                ('volume', models.CharField(max_length=155)),
                ('pageNumbers', models.CharField(max_length=155)),
                ('legislationTranscriptOriginal', models.FileField(upload_to='')),
                ('legislationTranscriptCopy', models.TextField()),
                ('place', models.CharField(max_length=255)),
            ],
        ),
    ]
