version: '3.4'

volumes:
  data01:
    driver: local
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: colegio_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
  
  colegioelasticsearch:
    build: .
    container_name: colegioelasticsearch
    volumes:
      - ./elastic/static:/app/static
      -  ./elastic/uploads:/app/uploads
    depends_on:
      - postgres
      - es01

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    expose:
      - "9200"

 
    
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: colegio_production_postgres
    expose:
      - "5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  

  