# Generated by Django 3.1.5 on 2021-01-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tpe_col_cattdisp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositionType', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tpe_col_cattdisps',
            },
        ),
    ]
